version: '3.7'
services:
  web_server:
    build: web_server
    ports:
      - 5000:80
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=macedonian_sentiment
      - PGDATA=/var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
       - 5432:5432
  adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
  pgdata:
  requirements.txt:
