name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7","3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r frontend/requirements.txt
        pip install -r web_server/requirements.txt 
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
  
  docker:
      - name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          version: '0.2.6-rc.1' # optional
          docker_compose: 'docker-compose.yml' # required
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
